### ISSUE TITLE
关于活动中掉落统计增加各难度掉落数据的建议

### ISSUE THREAD

**Issue by SmallFatSheep** [kcwikizh/poi-statistics#13]
目前的活动的掉落统计并没有各难度掉落的数据
若能像kancolledb一样在总掉落概率后加入各难度掉落数据,(总比率,甲S%,乙S%,丙S%)
则可以更加便于玩家区分哪些船是某种难度限定掉落的,以及各难度的掉落几率的差异.
这在某些船只只在限定难度掉落的大型活动中很有意义.

**Comment by Gizeta** [comment]
![+号的存在感](https://cloud.githubusercontent.com/assets/1572561/11291453/cbf199ae-8f83-11e5-8817-72d50d17692a.png)
实际上表格左边有个加号可以展开详细数据，里面会有一些更细的概率。
（“+”的存在感已经被一些人吐槽过了，以后可能会换个更醒目的方式吧）

**Comment by SmallFatSheep** [comment]
了解了,
加号确实能够反应出各难度掉落数据,
一般对于玩家来说每个图关注的也就几艘船,希望把+号做的更醒目些
