### ISSUE TITLE
…夏活的記錄都消掉了？

### ISSUE THREAD

**Issue by c933103** [kcwikizh/poi-statistics#14]
http://db.kcwiki.moe/drop/map/FS方面海域.html

**Comment by Gizeta** [comment]
因为在重构的原因所以普通图及夏活图的掉落数据停止更新了，我尽量在秋活之后补上这部分数据。
夏活统计的旧数据包括备份被我手贱删掉了，需要再重新生成一遍，所以暂时会没有数据。
