### ISSUE TITLE
建議增加一欄顯示該點/該難易度下所有敵方配置

### ISSUE THREAD

**Issue by c933103** [kcwikizh/poi-statistics#20]

**Comment by Gizeta** [comment]
唔，这个功能我觉得还是交给wiki去实现比较好，所以敌方配置只留出了生成wiki text code的接口。比如
 ``/wiki/enemy/341.html``

**Comment by RikaSugisawa** [comment]
> 
> 
> 唔，这个功能我觉得还是交给wiki去实现比较好，所以敌方配置只留出了生成 wikitext 的接口。比如
> `/wiki/enemy/341.html`

请问这个接口还有在提供吗？

**Comment by Gizeta** [comment]
> 
> 
> > 唔，这个功能我觉得还是交给wiki去实现比较好，所以敌方配置只留出了生成 wikitext 的接口。比如
> > `/wiki/enemy/341.html`
> 
> 请问这个接口还有在提供吗？

@RikaSugisawa 生成 wikitext 相关的接口已经都下掉了，如果需要这些数据可以去 [kcwiki](https://zh.kcwiki.org/wiki/2019%E5%B9%B4%E6%98%A5%E5%AD%A3%E6%B4%BB%E5%8A%A8/E-1) 上获取。
