### ISSUE TITLE
建議在掉落統計表增加下列欄目

### ISSUE THREAD

**Issue by c933103** [kcwikizh/poi-statistics#23]
1。　完全S勝率
2。　陣形數（已被記錄會掉落該艦娘的敵方陣形或排名總數）（排除不到1％的陣形）

**Comment by Gizeta** [comment]
1、完全胜利S 和 胜利S 在数据中均为S，无法区别。
2、阵型数可由掉落数量和掉落率推算得出。如果是研究阵型出现的比例，那会牵扯到C/D/E败的数据，暂时不会考虑做在掉落页面。
