### ISSUE TITLE
數據調閱請求

### ISSUE THREAD

**Issue by c933103** [kcwikizh/poi-statistics#25]
請求：可以搜索並總結一下在已收集的開發數據中，在油>20、彈>60、鋁>100、鋁>油、鋁>鋼、鋁>彈的情況下，如果秘書艦分別是a.)速吸[未改造]，或者b.)速吸改時，開發結果按裝備分項集計的結果，並分享該結果嗎？

**Comment by Gizeta** [comment]
如果有能力，建议自己建库查询。
我这里时间精力不是很多，按照优先程度可能不会很快返回结果。

如果我做完，会把结果贴在回复里。

**Comment by c933103** [comment]
已經進行相關搜索並得到0結果。
