### ISSUE TITLE
是否能将甲乙丙掉率并排显示

### ISSUE THREAD

**Issue by yj937745208** [kcwikizh/poi-statistics#27]
这样感觉更容易对比掉率，选择难度。每次对比都要重新按记住别的难度掉率感觉有点麻烦

**Comment by Gizeta** [comment]
现在一个页面有很多变量的话，表格会很难制作，除非丢弃一些信息。所以，目前不会考虑合并其他难度的数据。

如果是对比某一个舰娘的掉率的话，以后会制作单独的页面。（掉落首页右面的coming soon...，我知道soon很久了\_(:3」∠)\_
___
临时解决方法：
* 记录（截屏、记事本）
* 开多个窗口
* 看看有没有好心人写了掉落总结的帖子
