### ISSUE TITLE
Request to use some statistics

### ISSUE THREAD

**Issue by Acrone** [kcwikizh/poi-statistics#29]
Hello poi-statistics team,

I apologize if this is in the wrong place.

Over the past few days I have been working on a simple KanColle drop site to be able to quickly look up what shipgirls drop on map nodes. It is similar to the kcwiki [drop statistics](https://db.kcwiki.moe/drop/) page, however instead of providing regularly updated statistics, I am intending to provide quick lookup node data for the English KC players.

I am writing to you today to make a request to copy some of the statistics displayed on the drop statistics page. I am asking if it would be okay if I use the 掉落率 values that you provide for each map node. 
For example, on your site the data is displayed like [this](http://i.imgur.com/Dzh7JnI.png) while on my site the data is displayed like [this](http://i.imgur.com/rYWoVZz.png).

I will not be regularly querying your database, just wondering if it would be okay to copy the 掉落率 data you have on node drops into my own database and display it on my site.

If you would like to take a look at my site, you can find it [here](http://kc.acr.one/drops.php). _If you do, only map1-1 has node data in my database for testing._

Kind regards.

**Comment by Gizeta** [comment]
Hello.

There is no limit to use our data **for non-commercial use**. Feel free to copy, if you are not on the purpose of getting profit.

I'm working on writing API, so there is no API right now. You can crawl the web pages to get the data.

**Comment by Acrone** [comment]
Hi Gizeta,

I can assure you this is completely for non-commercial use and will be for the life of this small project.

Thank you for your response, approval to use this data is greatly appreciated.

Best of luck to you and the rest of the team!

Kind regards.
