### ISSUE TITLE
无法看到某些点的掉落数据

### ISSUE THREAD

**Issue by feidandeyaliya** [kcwikizh/poi-statistics#32]
测试就chorme浏览器有问题，一直祈祷中，手机上的chorme也不行，电脑上换其他浏览器就行，不知道什么原因

**Comment by Gizeta** [comment]
网站的大部分用户都是用chrome的，感觉应该不会是浏览器的锅。

麻烦提供一下chrome的版本及开发者工具 ( F12 或 Ctrl + Shift + I ) 的截图（如下图所示）
![default](https://cloud.githubusercontent.com/assets/1572561/25932090/a2cad72c-3642-11e7-8a91-bda1817c6c67.png)

**Comment by feidandeyaliya** [comment]
版本 57.0.2987.133
![default](https://cloud.githubusercontent.com/assets/28614603/25932534/c6d89e6a-364c-11e7-80ed-7a4a42cc183a.PNG)

**Comment by Gizeta** [comment]
活动图我都看过了没有这种问题。
建议清一下缓存。

出错原因大致猜测是https://db.kcwiki.org/scripts/drop/constant.js文件缓存了旧的版本（没有新船的信息）。

**Comment by feidandeyaliya** [comment]
谢谢，已解决
