### ISSUE TITLE
新beta版本和魔改有严重冲突

### ISSUE THREAD

**Issue by MasahiroLiu** [kcwikizh/poi-statistics#37]
新beta版本和魔改有严重冲突，不仅无法显示魔改立绘，甚至会导致游戏速度极度缓慢（一个战斗点大概得跑将近10分钟甚至更久）。
我的笔电与桌机同时发生这个情况，因此应该不是硬件问题。
附上新旧版本的截图佐证。
（秘书舰相同，但是旧版正常显示，新版秘书舰却离家出走）
旧的7.10.1正式版https://imgur.com/a/FkEwH
新的8.0.0beta1版https://imgur.com/a/bTFuQ

**Comment by Gizeta** [comment]
这里并不是 poi 的仓库，开发人员看不到的，有问题请发至 https://github.com/poooi/poi/issues

只能帮 @KochiyaOcean @KagamiChan

**Comment by KochiyaOcean** [comment]
8.0.0 今天已经发布正式版了，而且这个 bug 在 6 天前就被 8.0.0-beta.2 修复了……
