### ISSUE TITLE
previous dumps

### ISSUE THREAD

**Issue by Acrone** [kcwikizh/poi-statistics#38]
Good afternoon,

I was wondering if by any chance you had a historical dump or previous dumps from poidb that would be available. I am looking for previous poidb dropshiprecords, createshiprecords, and createitemrecords db dumps. I [asked](https://github.com/poooi/poi-server/issues/35#issue-300873275) over on poi-server earlier but yukixz informed me that data is lost when they clean their data due to server storage cost and to [ask the kcwiki team](https://github.com/poooi/poi-server/issues/35#issuecomment-369106551).

I am trying to collate as much poidb data as I can to get some large data sample sizes so we can pull information/statistics for the English KC community.

I am sorry if I am asking the wrong group, if so could you tell me who to contact.

Kind regards

**Comment by Gizeta** [comment]
Hello,

We also meet the storage problem, so we have no backups on the server. I had ever uploaded some of them to my personal dropbox(Baidu Net Disk, https://pan.baidu.com/s/1mjLmkv2). But, due to my laziness, I lost the backups from Jul. 2017 to Jan. 2018.

I can download them to my server if necessary so that you can download directly.

Hope this helps you.

**Comment by Acrone** [comment]
Hi Gizeta,

If you could download them to your server that would be very much appreciated! I can download from baidu, but at 5-30 KB/s >.<

Thank you for your help so far. These dumps are exactly what I was looking for!

Kind regards

**Comment by Acrone** [comment]
I was able to register an international account and used the Baidu client to download the dumps. Left it running over night and it seems the download speed picked up during off-peak hours.

Thank you so much for sharing the dumps you kept!

**Comment by gakada** [comment]
https://mega.nz/#F!WNY2BDpa!b7BQZx903X71kNnPG1aTeA

In case it is needed, there may be some data newer than July 2017.
