### ISSUE TITLE
poi掉落统计应该检查空余船位

### ISSUE THREAD

**Issue by ccxcxd** [kcwikizh/poi-statistics#4]
1-1 BOSS S胜无掉落是一件不可能的事情，只能想到是因为没有空船位了，这种数据应该从统计里去除。

**Comment by Gizeta** [comment]
数据库是没有船位信息的。我会去尝试和各位做插件的作者讨论解决。

**Comment by Gizeta** [comment]
时间有些古老了。。。
poi-server那边说没有必要，所以暂时不会考虑。
