### ISSUE TITLE
请问POI里面的语音翻译还在更新吗？

### ISSUE THREAD

**Issue by ccen3020** [kcwikizh/poi-statistics#43]
新版本里面很多都是数字.数字的格式了……
那面说是这面没有在更新了

**Comment by TrickLin** [comment]
请问具体来说 是哪个语音显示有问题呢

**Comment by ccen3020** [comment]
全新安装后第一次启动，下载完插件之后语音翻译没显示……
再启动一次就好了
看上去是加载不完全的样子？
