### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by wangyiyi121** [kcwikizh/poi-statistics#46]
根据谷歌的cache文件，20 Jun 2019 05:18:46 GMT的时候仍然能够访问网站，也就是说最早从那个时候开始出现的问题。现在貌似完全无法访问db（也许是数据库的问题？）
从kcwiki的评论来看，也许直到7小时前都是可以访问的

**Comment by wangyiyi121** [comment]
咱稍稍多加调查了一下，貌似咱连接的时候都会被转到45.79.90.229这个IP地址，而不是国内连接时用的212.64.82.54。也许是服务器问题

**Comment by wangyiyi121** [comment]
去弄了个国内IP地址来尝试连接，这次被转到了212.64.82.54就打开了网页，但是调用数据库时无限少女祈祷中并且Failed to get data
总之目前就是这样的状况：
外网连接被转到45.79.90.229，然后504 Gateway Time-out
外网通过搭桥转用内网IP连接，被转到212.64.82.54，能打开网页但是打不开数据库（咱测试时候用的桥是江苏省南京市 电信）
咱也尝试看了看源代码，但是就咱这点水平也找不出来数据库位置

**Comment by wangyiyi121** [comment]
再次检查，问题已解决，归档

**Comment by Gizeta** [comment]
hmmmm，没有去查现场，只知道重启了一下puma和nginx就好了，有时间会看看日志有什么蛛丝马迹。

怀疑是统计任务中MongoDB吃了太多内存，导致服务器抽风。

后续会考虑加个监测的脚本，访问异常就及时重启。
