### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Gizeta** [kcwikizh/poi-statistics#5]
- [x] 去除掉落中C/D/E败的数据
- [x] 重新整理KCConstants
- [x] 建造统计
  - [ ] 页面重新设计
- [x] 开发统计
- [x] 基于ObjectId的时间数据分析
- [x] 缓存上次查询数据，新旧数据分隔
- [ ] 对特定数据建立特定的查询规则
- [x] 更新bootstrap-table
- [ ] 重新设计活动页面及模型

**Comment by Gizeta** [comment]
- [ ] 活动图甲乙丙数据拆分到3个页面
- [ ] 增加敌舰队配置概率统计

**Comment by Gizeta** [comment]
- [ ] 使用mongo-hadoop代替MongoDB

**Comment by c933103** [comment]
- 拆分貌似不太分便縱向對比…除非用分頁切換難度而且讓同名艦娘在不同分頁出現在相同位置？
- 請顯示每細分數據項的母數（以掉落統計為例，顯示甲/乙/丙的S/A/B/所有名次的次數而非所有該點數據加總)

**Comment by Gizeta** [comment]
[ ] 整合kcdata
[ ] 恢复往期活动数据
[ ] 按ship id分类的掉落页面

**Comment by Gizeta** [comment]
这个issue搞得太乱了，有时间重新整理一下。先close掉。
