### ISSUE TITLE
7-3 掉落統計未出現在地圖中

### ISSUE THREAD

**Issue by NarihiroCH** [kcwikizh/poi-statistics#57]
直接訪問 URL( https://db.kcwiki.org/drop/map/73/P-SAB.html ) 可以看到 7-3 的掉落統計，但在地圖頁面( https://db.kcwiki.org/drop/ ) 選擇南西海域只能看到 7-1 和 7-2。

![image](https://user-images.githubusercontent.com/16795336/104831333-2f4b4700-58cb-11eb-80b8-f198ae8759b0.png)

**Comment by Gizeta** [comment]
fixed
