### ISSUE TITLE
德系船只的建造统计改为只统计德系秘书舰时的建造数据

### ISSUE THREAD

**Issue by JenningsWu** [kcwikizh/poi-statistics#6]
有个建议，BSM、Z3等船的出货统计仅考虑德系秘书舰下的情况大概比较好？

另外，可以的话也像岛风go那样，列一个各个旗舰出货概率排行？

**Comment by Gizeta** [comment]
第一条可以考虑。

第二条现在已经有了。
![+号的存在感。。。](https://cloud.githubusercontent.com/assets/1572561/9732149/709e535e-565c-11e5-97da-cb07b9d93da0.png)
