### ISSUE TITLE
db.kcwiki.cn/drop 页面载入问题,整个 页面载入不完整

### ISSUE THREAD

**Issue by cydad111** [kcwikizh/poi-statistics#64]
所有UI都没有,整个白色,上面只有数值,而且部分数据无法读取,一直初始化.

**Comment by cydad111** [comment]
整个感觉就是网站一直在线维护- -系统不稳定一样

**Comment by Gizeta** [comment]
这个问题现在是否还存在？

无法读取的时候有没有弹出加载失败的对话框？
如果没弹的话更像是网络方面的问题，有弹出的话大概率是页面问题，可以提供下具体的url。

“所有UI都没有,整个白色,上面只有数值”这个可以提供下截图

**Comment by cydad111** [comment]
GET https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css net::ERR_ABORTED 404 (Not Found)
db.kcwiki.cn/:2017 GET https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js net::ERR_ABORTED 404 (Not Found)

DevTools failed to load source map: Could not load content for https://static.kcwiki.org/db/scripts/chartist.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE db.kcwiki.cn/:2017 GET 
https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js net::ERR_ABORTED 404 (Not Found)
我提问过有人说因为去年12月21日,jsDelivr 的国内 ICP 吊销.所以要绕行HK

**Comment by cydad111** [comment]
有意思的是,那人建议我挂代理,但是我挂梯子都会这样- -

**Comment by Gizeta** [comment]
cdn链接都更新了，可以清缓存试下还有没有问题。

**Comment by cydad111** [comment]
可以了,感谢修复问题~
