### ISSUE TITLE
舰娘出货记录中应该过滤出货小于一定量的公式

### ISSUE THREAD

**Issue by magicae** [kcwikizh/poi-statistics#9]
比如出货如果小于10次就不要显示这个公式了，不然100%的公式太多，比较冗余，重要的公式找不到。

**Comment by SmallFatSheep** [comment]
支持!
母数小于一定数量的建造公式由于概率问题，看似是100％，且排在统计的前列，但实际几乎毫无参考价值，且会误导新人
